// Mapping from LAU/native city name to English display name
export const lauToEnglish = {
  "Ancona": "Ancona",
  "Barcelona": "Barcelona",
  "Berlin, Stadt": "Berlin",
  "Bologna": "Bologna",
  "Brussels": "Brussels",
  "Budapest": "Budapest",
  "Chisinau": "Chisinau",
  "Debrecen": "Debrecen",
  "Firenze": "Florence",
  "Gdańsk": "Gdansk",
  "Genova": "Genoa",
  "Grad Zagreb": "Zagreb",
  "Katowice": "Katowice",
  "Kraków": "Krakow",
  "Kyiv": "Kyiv",
  "København": "Copenhagen",
  "Lisbon": "Lisbon",
  "Lyon": "Lyon",
  "Madrid": "Madrid",
  "Milano": "Milan",
  "Municipiul București": "Bucharest",
  "Municipiul Sibiu": "Sibiu",
  "München, Landeshauptstadt": "Munich",
  "Oslo kommune": "Oslo",
  "Palermo": "Palermo",
  "Paris": "Paris",
  "Praha": "Prague",
  "Roma": "Rome",
  "Sevilla": "Seville",
  "Stockholm": "Stockholm",
  "Torino": "Turin",
  "Warszawa": "Warsaw",
  "Wien": "Vienna",
  "Wrocław": "Wroclaw",
  "Łódź": "Lodz",
  "Δημοτική Κοινότητα Αθηναίων": "Athens"
};

// Mapping from LAU/native city name to the CityStreetData file slug (without suffix)
// Ensure each entry corresponds to an existing file: CityStreetData/<slug>_enriched.json
export const lauToSlug = {
  "Ancona": "ancona",
  "Barcelona": "barcelona",
  "Berlin, Stadt": "berlin",
  "Bologna": "bologna",
  "Brussels": "brussels",
  "Budapest": "budapest",
  "Chisinau": "chisinau",
  "Debrecen": "debrecen",
  "Firenze": "firenze",
  "Gdańsk": "gdansk",
  "Genova": "genova",
  "Grad Zagreb": "zagreb",
  "Katowice": "katowice",
  "Kraków": "krakow",
  "Kyiv": "kyiv",
  "København": "københavn",
  "Lisbon": "lisboa",
  "Lyon": "lyon",
  "Madrid": "madrid",
  "Milano": "milano",
  "Municipiul București": "bucuresti",
  "Municipiul Sibiu": "sibiu",
  "München, Landeshauptstadt": "munchen",
  "Oslo kommune": "oslo",
  "Palermo": "palermo",
  "Paris": "paris",
  "Praha": "praha",
  "Roma": "roma",
  "Sevilla": "sevilla",
  "Stockholm": "stockholm",
  "Torino": "torino",
  "Warszawa": "warszawa",
  "Wien": "wien",
  "Wrocław": "wrocław",
  "Łódź": "łodz",
  "Δημοτική Κοινότητα Αθηναίων": "athene"
};

export const allCities = Object.keys(lauToSlug);
